---
title: "Project"
output: html_document
date: "2024-11-27"
---

```{r}
pro=read.csv('603 Project Dataset Clean 2001 Q2.csv')
head(pro)
```

```{r}
library(olsrr)
reg=lm(INDINF_AFFORD~INDINF_OUTGAPMPR_Q+INDINF_OUTGAPM_Q+INDINF_GRACE_Q+INDINF_FAM_WIOD_Q+Housing.Start+INDINF_SLSALLSEC_Q+INDINF_BOS_LSI_Q+INDINF_CPI_Q+INDINF_CPI_MEDIAN_Q+INDINF_CPI_COMMON_Q+INDINF_LFSWC_Q+INDINF_NACWC_Q+INDINF_PAWC_Q+INDINF_SEPHWC_Q+INDINF_WC_Q+INDINF_NHPI_Q+INDINF_FOURORMORE_Q+INDINF_ONEORLESS_Q+INDINF_THREEORLESS_Q+INDINF_TWOORLESS_Q+INDINF_ROS1TO2_Q+INDINF_ROS2TO3_Q+INDINF_ROSBELOW1_Q+INDINF_ROSOVER3_Q+INDINF_EXPECTSIXTEN_Q+INDINF_EXPECTTWOTHREE_Q+INDINF_INFEXP_BOND_Q+X10.Year.Bond,data=pro)
step=ols_step_both_p(reg,p_enter=0.01,p_remove=0.1,details=FALSE)
summary(step$model)
```

```{r}

plot(step$model)
library(lmtest)
bptest(step$model)
library(mctest)

imcdiag(step$model, method="VIF")
```
```{r}
reg2=lm(INDINF_AFFORD~(INDINF_GRACE_Q+INDINF_CPI_MEDIAN_Q+X10.Year.Bond+INDINF_OUTGAPMPR_Q+INDINF_SLSALLSEC_Q+INDINF_EXPECTTWOTHREE_Q)^2,data=pro)
summary(reg2)
```
```{r}
reg3=lm(INDINF_AFFORD~INDINF_GRACE_Q+INDINF_CPI_MEDIAN_Q+X10.Year.Bond+INDINF_OUTGAPMPR_Q+INDINF_SLSALLSEC_Q+INDINF_EXPECTTWOTHREE_Q+INDINF_GRACE_Q:X10.Year.Bond,data=pro)
summary(reg3)
```

```{r}
library(GGally)
df=data.frame(pro$INDINF_AFFORD,pro$INDINF_GRACE_Q,pro$INDINF_CPI_MEDIAN_Q,pro$X10.Year.Bond,pro$INDINF_OUTGAPMPR_Q,pro$INDINF_SLSALLSEC_Q,pro$INDINF_EXPECTTWOTHREE_Q)
ggpairs(df,lower = list(continuous = "smooth_loess", combo =
  "facethist", discrete = "facetbar", na = "na"))
```
```{r}
reg4=lm(INDINF_AFFORD~INDINF_GRACE_Q+INDINF_CPI_MEDIAN_Q+I(INDINF_CPI_MEDIAN_Q^2)+X10.Year.Bond+INDINF_OUTGAPMPR_Q+I(INDINF_OUTGAPMPR_Q^2)+INDINF_SLSALLSEC_Q+INDINF_EXPECTTWOTHREE_Q+INDINF_GRACE_Q:X10.Year.Bond,data=pro)
summary(reg4)
```
```{r}
reg5=lm(INDINF_AFFORD~INDINF_GRACE_Q+INDINF_CPI_MEDIAN_Q+I(INDINF_CPI_MEDIAN_Q^2)+X10.Year.Bond+INDINF_OUTGAPMPR_Q+I(INDINF_OUTGAPMPR_Q^2)+INDINF_EXPECTTWOTHREE_Q+INDINF_GRACE_Q:X10.Year.Bond,data=pro)
summary(reg5)
print(anova(reg5,reg4))
```
```{r}
reg6=lm(INDINF_AFFORD~INDINF_GRACE_Q+INDINF_CPI_MEDIAN_Q+I(INDINF_CPI_MEDIAN_Q^2)+X10.Year.Bond+INDINF_OUTGAPMPR_Q+I(INDINF_OUTGAPMPR_Q^2)+INDINF_EXPECTTWOTHREE_Q+INDINF_GRACE_Q:X10.Year.Bond,data=pro)
summary(reg6)
```

